### ISSUE TITLE
Xgboost controller is going to error state due to wrong CRD file

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/xgboost-operator#115]
Original issue: https://github.com/kubeflow/manifests/issues/1728

Moving here as it's an issue with xgboost-operator manifests.

Copying what @hemantha-kumara said:

xgboost controller is failing with the below reason

```
{"level":"error","ts":1611742542.4809206,"logger":"entrypoint","msg":"unable to run the manager","error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/xgboost-operator/cmd/manager/main.go:82\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```

manifest CRD(https://github.com/kubeflow/manifests/blob/master/xgboost-job/xgboost-operator/base/crd.yaml & https://github.com/kubeflow/manifests/blob/v1.2-branch/xgboost-job/xgboost-operator/base/crd.yaml ) should be updated with https://github.com/kubeflow/xgboost-operator/blob/master/config/crds/xgboostjob.kubeflow.org_xgboostjobs.yaml

**Comment by yanniszark** [comment]
cc @kubeflow/wg-training-leads

**Comment by yanniszark** [comment]
https://github.com/kubeflow/xgboost-operator/blob/master/manifests/base/kustomization.yaml

```yaml
- name: gcr.io/kubeflow-images-public/xgboost-operator
  newName: gcr.io/kubeflow-images-public/xgboost-operator
  newTag: vmaster-g56c2c075
```

the above docker is having changes to work with xgboost crd version v1 but the crd present in the URL https://github.com/kubeflow/xgboost-operator/blob/master/manifests/base/crd.yaml is having v1alpha1

**Comment by yanniszark** [comment]
Copying another comment from @hemantha-kumara:

Changing the docker version to gcr.io/kubeflow-images-public/xgboost-operator:v0.1.0 should solve the issue. But this is only a workaround not the fix for the issues present in the xgboost-operator repo
kubeflow/xgboost-operator#108
kubeflow/xgboost-operator#92

**Comment by yanniszark** [comment]
Pinging OWNERS:
@terrytangyuan @richardsliu @merlintang @johnugeorge

How should this issue be resolved? Please advise.

**Comment by yanniszark** [comment]
@hemantha-kumara maybe it makes sense to open a PR with your workaround?

**Comment by hemantha-kumara** [comment]
Yes, till we fix and release the new docker image. changing back docker to the older version will unblock the xgboost operator issue.

**Comment by Jeffwan** [comment]
When is the deadline? I think I can help fix this issue.

**Comment by andreyvelich** [comment]
@Jeffwan Should be March 23rd. On the community meeting right now we should decide the date.

**Comment by thesuperzapper** [comment]
To all watching, this is a blocking issue for Kubeflow 1.3.

In the community meeting we all committed to resolving it before end-of-day  __2021-03-24 [California time]__ (tomorrow), what needs to be done for a PR to get merged @yanniszark ? 

I am happy to help, if needed.

**Comment by Jeffwan** [comment]
I will file a PR by this afternoon

**Comment by Jeffwan** [comment]
The major reason user see this failure is because we use v1alpha1 in past release 1.2. However, master has been changed to v1 at that time. CI triggers build and override image tag. 

This can be easily changed to use new generated v1 crd. Waiting for PR #116 to be merged
