### ISSUE TITLE
Only can run with WORLD_SIZE = 2

### ISSUE THREAD

**Issue by AmberCheng** [kubeflow/xgboost-operator#30]
hi, 
I have tried the distributed example(xgboost-dist-iris) on k8s cluster. I have set MASTER_ADDR, MASTER_PORT, RANK, and WOLRD_SIZE. As I set WOLRD_SIZE=2; I can get the distribute demo run and finished with one Master and one worker. But when I set  WOLRD_SIZE=3, I can not run it with one Master and two workers. They seem to wait for each other, stop at log  'starting to train xgboost at node with rank 0'. Does anyone have any idea about it?

**Comment by merlintang** [comment]
Hi, do you change the yaml file https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml#L30. you need to change this to your defined work_size. meanwhile, you do not need to modify this parameter in your application code, the controller would generate this env for you based on your yaml file.

**Comment by AmberCheng** [comment]
> Hi, do you change the yaml file https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml#L30. you need to change this to your defined work_size. meanwhile, you do not need to modify this parameter in your application code, the controller would generate this env for you based on your yaml file.

I don't have set the work_size..Do you mean world_size?

**Comment by merlintang** [comment]
yes, WOLRD_SIZE. you do not need to change WOLRD_SIZE. this is provided by controller.
