### ISSUE TITLE
Is there a simple way to install the XGBoost Operator without installing Go and building from source?

### ISSUE THREAD

**Issue by cfregly** [kubeflow/xgboost-operator#31]
current install is a bit complex for the masses.

**Comment by terrytangyuan** [comment]
We can push [the docker image](https://github.com/kubeflow/xgboost-operator/blob/master/Dockerfile) to Dockerhub. And then you can just deploy the kubebuilder manager, crds and rbac [here](https://github.com/kubeflow/xgboost-operator/tree/master/config) to your cluster with `kubectl`. Would that be sufficient?

**Comment by cfregly** [comment]
yes, that would lower the barrier to entry for this operator.

**Comment by cfregly** [comment]
also, the current yaml creates a `system` namespace.  this is very generic.  can you rename to `xgboost-system`?

**Comment by jlewi** [comment]
See also kubeflow/manifests#229 to add a kustomize manifest.

A kustomize manifest would allow it to be easily installed as part of Kubeflow deployments. 
It should be fairly straightforward to turn your YAML manifests into a kustomize package.

To @cfregly's point the current pattern in Kubeflow is that all shared components (e.g. job oeprators) are installed in the "kubeflow" namespace.

Users would then consume those operators in their own namespace.
