### ISSUE TITLE
Change repo name from xgboost to xgboost-operator 

### ISSUE THREAD

**Issue by merlintang** [kubeflow/xgboost-operator#4]
As we discussed in the [proposal](https://github.com/kubeflow/community/issues/247), the repo name would be xgboost-operator. thus, @jlewi   can you revise this.

**Comment by terrytangyuan** [comment]
@jlewi Could you rename the repo when you get a chance?

**Comment by jlewi** [comment]
Name has been changed.
https://github.com/kubeflow/xgboost-operator
