### ISSUE TITLE
XgB operator distributed training?

### ISSUE THREAD

**Issue by Rajneesh-Tiwari** [kubeflow/xgboost-operator#41]
How do we understand if the training is distributed across nodes. Right now, I am doing experiment on IRIS dataset, and the worker logs are all empty.  Training logs show the right stuff, meaning training etc, however, my intention is to use the worker nodes as well to train.

Any help on this matter is appreciated.

**Comment by merlintang** [comment]
hi @Rajneesh-Tiwari , the training is working via distributed way, you can notice that each worker only load part of iris data for his pod.

**Comment by Rajneesh-Tiwari** [comment]
Many thanks for the reply @merlintang. I am streamlining my query below: 

How the data is distributed among the worker nodes? Is it master fetching the full data and then its partitioned among workers or data is fetched by the workers separately?

In our case, data is distributed in HDFS. So we can not load whole data in master to distribute within workers (if that is indeed the case).  Any thoughts on how we can go about this?

**Comment by merlintang** [comment]
you can assign each worker to read part of hdfs data. for example, each
worker has an index like rank, then, this rank can be used to fetch the
data. For HDFS, it is partitioned via the directory, then, each worker can
read subdirectory data independently

**Comment by Rajneesh-Tiwari** [comment]
@merlintang Thank you, that helps. I will close this thread for now.
