### ISSUE TITLE
Add the Installation part in the homepage readme  

### ISSUE THREAD

**Issue by merlintang** [kubeflow/xgboost-operator#57]
For beginner to start the xgboost operator easily, we would add the introduction in the begin of the readme, like the installation guide in [MPI-operator](https://github.com/kubeflow/mpi-operator#installation)

**Comment by merlintang** [comment]
@xfate123

**Comment by xfate123** [comment]
In order to let beginner to start xgboost operator easily by using git clone, do we need to create a xgoost-operator.yaml file to add crd config, cluster-role config, cluster-role-binding config ,service account config and deployment config all together?

**Comment by merlintang** [comment]
yes, it seems a good idea that we have everything in one yaml file for
simplicity.

**Comment by merlintang** [comment]
close this one.
