### ISSUE TITLE
Provide the docker image in the dockerhub

### ISSUE THREAD

**Issue by merlintang** [kubeflow/xgboost-operator#58]
Build the docker image and update the docker image in the reader me. 

FYI: 
https://github.com/kubeflow/mpi-operator#docker-images

**Comment by merlintang** [comment]
@XinkaiWang515

**Comment by terrytangyuan** [comment]
It’s already automatically published to https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/xgboost-operator?gcrImageListsize=30 so I don’t think it’s necessary to publish on Dockerhub.

**Comment by merlintang** [comment]
ok, let me close this one.
