### ISSUE TITLE
app.kubernetes.io labels on every resource

### ISSUE THREAD

**Issue by merlintang** [kubeflow/xgboost-operator#60]
Part of https://github.com/kubeflow/xgboost-operator/issues/44 for graduation 

Every resource that is part of the application should include the labels recommended by Kubernetes, currently:
app.kubernetes.io/name
app.kubernetes.io/instance
app.kubernetes.io/version
app.kubernetes.io/component
app.kubernetes.io/part-of
app.kubernetes.io/managed-by

**Comment by merlintang** [comment]
@xfate123

**Comment by terrytangyuan** [comment]
I think this is already done but please double check.

**Comment by merlintang** [comment]
en it seems this is fixed. can we update the graduate PR .s.t this point is fixed. https://github.com/kubeflow/xgboost-operator/issues/44

**Comment by terrytangyuan** [comment]
Done
