### ISSUE TITLE
XGBoost Serving?

### ISSUE THREAD

**Issue by ellis-bigelow** [kubeflow/xgboost-operator#7]
Hey All,
There's a group of folks working on XGBoost serving (i.e., serving from a static .bst or custom built container) over at https://github.com/kubeflow/kfserving. 

I noticed that the proposal mentioned "deploy" and "predict". 

I see prediction as two areas:
1. batch prediction (map function over a set of inputs)
2. online prediction (request/response style prediction)

Is there any room for collaboration or deduping, or have I misunderstood the charter of this repo

**Comment by terrytangyuan** [comment]
Hi @ellis-bigelow, thanks for reaching out! We’d love to collaborate and reuse the serving component. What’s the progress of that so far? Please share any references to design docs and demos if you have any.

**Comment by ellis-bigelow** [comment]
There are extensive docs in our repo. Cone take a look. We also have a
weekly meeting on Weds if you'd like to join.

*From: *Yuan (Terry) Tang <notifications@github.com>
*Date: *Sat, May 11, 2019, 12:21 PM
*To: *kubeflow/xgboost
*Cc: *Ellis Bigelow, Mention

Hi @ellis-bigelow <https://github.com/ellis-bigelow>, thanks for reaching

**Comment by merlintang** [comment]
@ellis-bigelow For this repo, we focus on the batch prediction. But of course, we would like to use the service model for online prediction.

**Comment by ellis-bigelow** [comment]
Makes sense!

**Comment by terrytangyuan** [comment]
Closing this for now. Let's create separate issues if further discussion on specific issues is needed.

**Comment by hzy001** [comment]
I have implemented [XGBoost Serving](https://github.com/iqiyi/xgboost-serving) that is a fork of TensorFlow Serving. It supports serving XGBoost models and XGBoost && FM models. You can read the README for more details and try it in a few minutes. If you encounter any problems, please submit an issue or email me directly.

**Comment by merlintang** [comment]
hi, can you illustrate how to use xgboost operator to train a model, and deploy it to the xgboost server @hzy001 ? 

thanks 

Mingjie
