### ISSUE TITLE
Issues on kubeflow/common migration

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/xgboost-operator#83]
xgboost-operator is a little bit different from other projects. 

1. v1alpha1 is built with kubebuilder. It uses 201906 version of kubeflow/common
2. In v1, we plan to upgrade kubeflow/common to latest version which is not compatible with the version used in v1alpha1.

That means if we probably need to delete v1alpha1 or migrate kubeflow/common to both folders which is still breaking change. 

@merlintang @terrytangyuan  Any opnions?

**Comment by terrytangyuan** [comment]
I think it's fine to delete v1alpha1 here if that's something we have to do to upgrade. We had a release for v1alpha1 so it should be okay to delete.

**Comment by Jeffwan** [comment]
sounds good.

**Comment by merlintang** [comment]
me too

**Comment by merlintang** [comment]
@Jeffwan hi jeff, does this migration finish? @xfate123 can you test on the migration based on the given example ?

**Comment by xfate123** [comment]
@merlintang For sure, my pleasure

**Comment by merlintang** [comment]
@Jeffwan can you update the example as well?

**Comment by Jeffwan** [comment]
@merlintang Yep. I should be able to clean up everything by end of week.

**Comment by Jeffwan** [comment]
#96 fixed manifest generation and out outdated crds issue.

**Comment by Jeffwan** [comment]
manifests are update to date. We migrate to v1 now. This issue can be closed
