### ISSUE TITLE
Set up auto update for image tag in manifests

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/xgboost-operator#89]
Some context: https://github.com/kubeflow/xgboost-operator/pull/88#issuecomment-637908990

The XGBoost operator's manifests in kubeflow/manifests should be automatically updated with newly built images in GCP.

Reference: https://github.com/kubeflow/testing/blob/master/apps-cd/applications.yaml

**Comment by pingsutw** [comment]
@terrytangyuan Could we close it?
I don't know how to close it. I don't see the close button in Github
