### ISSUE TITLE
xgboost-operator selector does not match template labels

### ISSUE THREAD

**Issue by yantriks-edi-bice** [kubeflow/xgboost-operator#91]
I tried to install xgboost-operator in my GCP kubeflow cluster (version 1.0.2 but possibly not fully)

YNTKLLC-EDI:xgboost-operator edibice$ kubectl kustomize base | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/xgboostjobs.xgboostjob.kubeflow.org created
serviceaccount/xgboost-operator-service-account created
clusterrole.rbac.authorization.k8s.io/xgboost-operator-cluster-role created
clusterrolebinding.rbac.authorization.k8s.io/xgboost-operator-cluster-role-binding created
configmap/xgboost-operator-xgboost-operator-config-tbkdd6997c created
service/xgboost-operator-service created
The Deployment "xgboost-operator-deployment" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"xgboost-operator"}: `selector` does not match template `labels`

**Comment by yantriks-edi-bice** [comment]
Following fixed the issue

diff --git a/xgboost-job/xgboost-operator/base/deployment.yaml b/xgboost-job/xgboost-operator/base/deployment.yaml
index 44d0dd3..02b1a59 100644
--- a/xgboost-job/xgboost-operator/base/deployment.yaml
+++ b/xgboost-job/xgboost-operator/base/deployment.yaml
@@ -6,7 +6,7 @@ spec:
   replicas: 1
   selector:
     matchLabels:
-      name: xgboost-operator
+      app: xgboost-operator
   template:
     metadata:
       labels:

**Comment by merlintang** [comment]
thanks @yantriks-edi-bice can you send a PR to fix this ? I am so glad the merge this.

**Comment by xfate123** [comment]
@merlintang  I have already sent a PR for this in Kubeflow/manifest repository couple 14 days ago, but have been approved yet

**Comment by terrytangyuan** [comment]
Thanks. @xfate123 I just approved it. Next time please tag me otherwise it's easy to miss.

**Comment by xfate123** [comment]
@terrytangyuan Appreciate it. I will cc you for sure next time. Thank you so much

**Comment by terrytangyuan** [comment]
Fixed via https://github.com/kubeflow/manifests/pull/1223
