### ISSUE TITLE
why the name of  xgboost-operator’s group is "xgboostjob.kubeflow.org"

### ISSUE THREAD

**Issue by Mesilenceki** [kubeflow/xgboost-operator#94]
Since both pytorch-operator and tf-operator’s group name are "kubeflow.org", shouldn’t xgboost-operator keep consistent with them? Appreciate any reply, thanks a lot. @terrytangyuan

**Comment by Mesilenceki** [comment]
Urgent case, appreciate for your response ASAP.@terrytangyuan

**Comment by terrytangyuan** [comment]
Good catch. I am fixing it in https://github.com/kubeflow/xgboost-operator/pull/95
