### ISSUE TITLE
Can the train code be develop in R?

### ISSUE THREAD

**Issue by velascoluis** [kubeflow/xgboost-operator#98]
Hi, im wondering if we can package and submit R code to the operator?

**Comment by terrytangyuan** [comment]
Yes but you'll need to write the data-worker distribution logic yourself. Another route is that you can use the [reticulate](https://github.com/rstudio/reticulate) package that we developed earlier to mix R+Python code and then use xgboost-operator for the execution of workloads.

**Comment by velascoluis** [comment]
Thanks Yuan, very interesting!
