### ISSUE TITLE
fail to install xgboost-operator

### ISSUE THREAD

**Issue by trieuat** [kubeflow/xgboost-operator#99]
I try to install the xgboost operator following the instructions (kustomize build base | kubectl apply -f -). However, the container failed to start with the error ("no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1alpha1\") as below. I would greatly appreciate if you could give some insights on how to fix it. I can see the CRD xgboostjob**s**.kubeflow.org in my CRD list.

> {"level":"error","ts":1595262600.3077261,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":{"Group":"xgboostjob.kubeflow.org","Kind":"XGBoostJob"},"error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/source/source.go:89\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:122\ngithub.com/kubeflow/xgboost-operator/pkg/controller/xgboostjob.add\n\t/go/src/github.com/kubeflow/xgboost-operator/pkg/controller/xgboostjob/xgboostjob_controller.go:150\ngithub.com/kubeflow/xgboost-operator/pkg/controller/xgboostjob.Add\n\t/go/src/github.com/kubeflow/xgboost-operator/pkg/controller/xgboostjob/xgboostjob_controller.go:66\ngithub.com/kubeflow/xgboost-operator/pkg/controller.AddToManager\n\t/go/src/github.com/kubeflow/xgboost-operator/pkg/controller/controller.go:28\nmain.main\n\t/go/src/github.com/kubeflow/xgboost-operator/cmd/manager/main.go:68\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
{"level":"error","ts":1595262600.307984,"logger":"entrypoint","msg":"unable to register controllers to the manager","error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/xgboost-operator/cmd/manager/main.go:69\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}

**Comment by merlintang** [comment]
@Jeffwan does this related to the update to v1. I do not see this error before.

**Comment by trieuat** [comment]
@merlintang do you have any suggestions on how to fix it? I can spend time to look into it but I am new to operators.

**Comment by Jeffwan** [comment]
/cc @Jeffwan 

Checking

**Comment by Jeffwan** [comment]
@trieuat 

I don't have any issues install it. 

```
kustomize build base | kubectl apply -f -                        
customresourcedefinition.apiextensions.k8s.io/xgboostjobs.kubeflow.org created
serviceaccount/xgboost-operator-service-account created
clusterrole.rbac.authorization.k8s.io/xgboost-operator-cluster-role created
clusterrolebinding.rbac.authorization.k8s.io/xgboost-operator-cluster-role-binding created
configmap/xgboost-operator-xgboost-operator-config-tbkdd6997c created
service/xgboost-operator-service created
deployment.apps/xgboost-operator-deployment created
```

> start with the error ("no matches for kind "XGBoostJob" in version "xgboostjob.kubeflow.org/v1alpha1") 

You are not supposed to see v1alpha1. I think @terrytangyuan has updated controller to v1 and give v1 CRD in kubeflow/manifests.

Could you give more details on your CRD version and controller image tag?


@merlintang I don't see this issue if I follow readme. It's probably user uses mismatched controller and CRD (for example, didn't clean up resources, etc)

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/manifests/commit/e15922e4c63fb17f745c3979a63ef8eb82e12c19

I think we changed group in this PR. 
https://github.com/kubeflow/manifests/commit/e15922e4c63fb17f745c3979a63ef8eb82e12c19

However, V1 CRD still use it. I think we can make v1 work first and then regenerate manifest with `kubeflow.org` as group later.

**Comment by terrytangyuan** [comment]
@Jeffwan Thanks for looking into this. @trieuat Please try what @Jeffwan mentioned above and let us know if you are still having issues.

**Comment by hamedhsn** [comment]
@Jeffwan @terrytangyuan I am trying to install the operator from the manifest and I am getting errors for v1.2.0 as well as master. any idea?
```
~/kustomize build xgboost-operator/overlays/application | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/xgboostjobs.xgboostjob.kubeflow.org created
serviceaccount/xgboost-operator-service-account created
clusterrole.rbac.authorization.k8s.io/xgboost-operator-cluster-role created
clusterrolebinding.rbac.authorization.k8s.io/xgboost-operator-cluster-role-binding created
configmap/xgboost-operator-xgboost-operator-config-6ct58987ht created
service/xgboost-operator-service created
deployment.apps/xgboost-operator-deployment created
application.app.k8s.io/xgboost-operator created
```
log:
```
kl xgboost-operator-deployment-59495c9854-zgpgh
{"level":"info","ts":1609759383.411976,"logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":1609759383.4121592,"logger":"entrypoint","msg":"setting up manager"}
{"level":"info","ts":1609759384.0154142,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1609759384.015574,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1609759384.0155895,"logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":1609759384.0157025,"logger":"entrypoint","msg":"Setting up controller"}
{"level":"info","ts":1609759384.0157304,"logger":"controller","msg":"Running controller in in-cluster mode"}
there is an error for the input config
{"level":"info","ts":1609759384.0158665,"logger":"controller","msg":"gang scheduling is set: ","gangscheduling":false}
{"level":"info","ts":1609759384.0159233,"logger":"entrypoint","msg":"setting up webhooks"}
{"level":"info","ts":1609759384.01593,"logger":"entrypoint","msg":"Starting the Cmd."}
{"level":"info","ts":1609759384.0162542,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1609759384.0163705,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"xgboostjob-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1609759386.1145597,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"XGBoostJob.xgboostjob.kubeflow.org","error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/internal.go:477"}
{"level":"error","ts":1609759386.1146486,"logger":"entrypoint","msg":"unable to run the manager","error":"no matches for kind \"XGBoostJob\" in version \"xgboostjob.kubeflow.org/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/kubeflow/xgboost-operator/cmd/manager/main.go:82\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```

```
k get crds
NAME                                         CREATED AT
applications.app.k8s.io                      2020-12-18T15:00:13Z
xgboostjobs.xgboostjob.kubeflow.org          2021-01-04T11:22:57Z
```

**Comment by souvik-deepsource** [comment]
@Jeffwan @terrytangyuan Experiencing the same errors as @hamedhsn.

**Comment by Jeffwan** [comment]
@souvik-deepsource  Please have a try with following commands.  This should be pretty stable now. Feel free to reopen the issue

```
cd manifests
kubectl create namespace kubeflow
kustomize build base | kubectl apply -f -
```
